### PR TITLE
UX: Tweak .tc-msgactions CSS

### PR DESCRIPTION
**Pull request by CvX**
* No double border
* All button have the same width
* "…" button has the same color

Before / After
Screen Shot 2021-12-23 at 22 43 12 Screen Shot 2021-12-23 at 22 36 06

updated After:

Screen Shot 2021-12-24 at 00 18 48

### CODE REVIEW

**Comment by jjaffeux** [comment]
Dont like this much more to be honnest 🤷‍♂️

What about we remove the border, on normal state and have it on reacted/hover ?

**Comment by SamSaffron** [comment]
I feel this is a bit too subtle ... maybe @jordanvidrine / @awesomerobot can provide feedback post holidays.

**Review by SamSaffron — APPROVED** [review]

**Comment by CvX** [comment]
Update:

2E91E985-ACBF-4AF1-9634-01B28FB871F6_1_102_o

**Comment by CvX** [comment]
Update:

Screen Shot 2021-12-24 at 00 18 48

**Comment by SamSaffron** [comment]
unlclear ... from your mobile pic it looks like you did not remove the border? or are you posting the current state?

**Comment by CvX** [comment]
That was a wrong screenshot, I removed that comment 😛

**Comment by jjaffeux** [comment]
Like it now 👌👌👌

**Pull request merged**
