### PR TITLE
FIX: Hook to event instead of model callback to make sure we auto-join users

### PR DESCRIPTION
**Pull request by romanrizzi**

### CODE REVIEW

**Comment by jjaffeux** [comment]
Is it really more sure? Can't a user be made active by other means?

**Comment by romanrizzi** [comment]
> Is it really more sure? Can't a user be made active by other means?

This is the only point where activation happens outside of creation AFAIK. All the other places assume email is valid when creating.

**Comment by jjaffeux** [comment]
> > Is it really more sure? Can't a user be made active by other means?
> 
> This is the only point where activation happens outside of creation AFAIK. All the other places assume email is valid when creating.
> 
> The problem with the previous callback is that it wasn't running when using `save!` instead of `update!`

Ok, honestly I'm not fan of having to trigger an event ourselves, if implementation changes we might not cache it in the test. OK yo merge this, but if you can think of a better test that would be great 🙌

**Comment by romanrizzi** [comment]
> Ok, honestly I'm not fan of having to trigger an event ourselves, if implementation changes we might not cache it in the test. OK to merge this, but if you can think of a better test that would be great 🙌

Yes, that's a good suggestion. Thanks! I added a test that calls the account activation controller 👌

**Pull request merged**
