### PR TITLE
DEV: Introduce PR template

### PR DESCRIPTION
**Pull request by nattsw**
To minimize UI bugs /65598

### CODE REVIEW

**Comment by jjaffeux** [comment]
It's ironic to have a flakey on this :D

**Comment by jjaffeux** [comment]
Do we actually had a lot of cases of specific bugs in firefox/safari ?

**Comment by jjaffeux** [comment]
Mostly I just think:

```
### Browsers

- [ ] safari
- [ ] chrome
- [ ] firefox

### Device

- [ ] desktop – wide screen
- [ ] mobile – `?mobile_view=1
```

Is general recommendation, not specific to chat

**Comment by jjaffeux** [comment]
And even if I added it ember-cli/legacy is also not specific to chat

**Review by jjaffeux — APPROVED** [review]

**Comment by jjaffeux** [comment]
Im liking the list but feels like a lot of it is part of general Discourse work, maybe we should backport part of it in discourse/discourse ?

It's ok to have an extended list here.  Maybe we also add the test part of discourse/discourse in this template too?

**Comment by nattsw** [comment]
> a lot of cases of specific bugs in firefox/safari ?

I believe the one that I know of for Safari is related to [scrolling](https://github.com/discourse/discourse-chat/pull/472), and [copy/pasting](https://github.com/discourse/discourse-chat/pull/718).

For Firefox, my earlier style for `fit-content` required something moz-specific which I just randomly decided to test and it indeed failed.

**Comment by nattsw** [comment]
Thank you

**Pull request merged**
