### PR TITLE
FIX: correctly displays unread indicator in titles

### PR DESCRIPTION
**Pull request by jjaffeux**

### CODE REVIEW

**Review by CvX — APPROVED** [review]

**Comment by jjaffeux** [comment]
Screenshot 2022-06-29 at 18 26 29
Screenshot 2022-06-29 at 18 27 36
Screenshot 2022-06-29 at 18 25 41

**Comment by CvX** [comment]
Hm, so we're back to the design where indicators are next to labels? 😃

iirc, it was like that originally. Then we decided it's too close to avatars (that use green as status indicators) so we moved them all the way to the right (+ a margin). We're reverting that change? cc: @discourse/designers (gotta try the new team mention 😛)

**Comment by jordanvidrine** [comment]
> Hm, so we're back to the design where indicators are next to labels? 😃
> 
> 
> 
> iirc, it was like that originally. Then we decided it's too close to avatars (that use green as status indicators) so we moved them all the way to the right (+ a margin). We're reverting that change? cc: @discourse/designers (gotta try the new team mention 😛)

I'm not seeing any change in the placement of the green/blue unread indicator here.

**Comment by jjaffeux** [comment]
really ? I tried how it was before my PR and it was next to label, I guess it was not  in non-sidebar... what a hell...

**Comment by jjaffeux** [comment]
Really we can't have such big difference between sidebas/non sidebars, it makes 0 sense

**Pull request merged**
