### PR TITLE
FIX: Don't hide the new messages indicator beside the channel header

### PR DESCRIPTION
**Pull request by romanrizzi**
Reintroduces discourse/discourse-chat#818, which was reverted on discourse/discourse-chat#826.

### CODE REVIEW

**Comment by jjaffeux** [comment]
What is the difference so far?

**Comment by romanrizzi** [comment]
I'm still trying to reproduce the issue locally 😞

**Comment by jjaffeux** [comment]
> I'm still trying to reproduce the issue locally 😞

At the very least I think you need two browser windows with lots of messages (rake chat:populate:messages) and then type a message

**Review by jjaffeux — APPROVED** [review]

**Comment by jjaffeux** [comment]
Ok let's try this

**Pull request merged**
