### PR TITLE
UX: Full-page & exit button changes

### PR DESCRIPTION
**Pull request by jordanvidrine**
This PR adjusts the look slightly for chat on full page with a non sidebar theme. It also applies consistent hover styling to the exit chat button.

### After
image

### Before
image

### CODE REVIEW

**Review by eviltrout — APPROVED** [review]

**Comment by CvX** [comment]
How does it look like when there's a banner, e.g. "emails disabled"?

**Comment by jordanvidrine** [comment]
> How does it look like when there's a banner, e.g. "emails disabled"?

great question. Do you know how I can get this, or another banner, showing up on a local instance?

**Comment by CvX** [comment]
e.g. set "disable emails" site setting to "yes", or set "global notice" setting to anything

**Comment by jordanvidrine** [comment]
> e.g. set "disable emails" site setting to "yes", or set "global notice" setting to anything

image

**Review by CvX — APPROVED** [review]

**Pull request merged**
